[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codecrafters-sqlite"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.0"
dependencies = [
    "sqlparse",
]

